Capped percent complete in monitor.c
zmap/zmap pull request #825
Opened 2024-03-15 19:16 UTC by phillip-stephens

Resolves #823 

This seems a bit ham-fisted, but I'm not sure what our alternative is. For some CLI parameters (`-N`) we don't know exactly how many packets we'll need to send.

2024-03-15 19:17 UTC, phillip-stephens commented
LMK what you think @zakird or if you see an alternative, nothing immediately sprung to mind.

2024-03-15 20:16 UTC, zakird approved these changes

2024-03-15 21:48 UTC, zakird requested changes
We should change to loop once (call `min_d` only once)

2024-03-15 21:53 UTC, phillip-stephens commented
Addressed!

2024-03-16 00:05 UTC, zakird approved these changes

2024-03-16 00:05 UTC, merged